### ISSUE TITLE
`TypeError: Cannot read properties of null (reading 'off')` during mount when running tests for a wrapper component

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [agilgur5/react-signature-canvas#81]
Hello and thank you so much for your work on this project! I am creating a wrapper around the `react-signature-canvas` and am working on writing jest tests for it with `testing-libarary/react`. I am simply trying to mount it to ensure it displays properly and am receiving the following error. I'm not passing anything to it besides a `ref` (created with `useRef`); I'm not even touching `canvasProps` (at this point). I am rendering the parent `<div />` with a `data-testid` so that I can grab hold of it in testing-library.

Test Code:
```tsx
describe('Signature', () => {
  it('Component renders successfully', () => {
    render(<Signature SubmitComponent={() => <div />} />);
    const sigCanvas = screen.getByTestId('react-signature-canvas');

    expect(sigCanvas).toBeInTheDocument();
  });
});
```

(`Signature` is my wrapper component, this is what I'm actually rendering `<SignatureCanvas ref={canvasRef} {...canvasAttributes} />` but `canvasAttributes` is `null` in my test above.)

<details>
  <summary>Stack trace:</summary>
  
```
 ● Signature › Component renders successfully

    TypeError: Cannot read properties of null (reading 'off')

       5 | describe('Signature', () => {
       6 |   it('Component renders successfully', () => {
    >  7 |     render(<Signature SubmitComponent={() => <div />} />);
         |     ^
       8 |     const sigCanvas = screen.getByTestId('react-signature-canvas');     
       9 |
      10 |     expect(sigCanvas).toBeInTheDocument();

      at t.r.off (../../node_modules/react-signature-canvas/build/index.js:1:3228) 
      at t.value (../../node_modules/react-signature-canvas/build/index.js:1:3771) 
      at callComponentWillUnmountWithTimer (../../node_modules/react-dom/cjs/react-dom.development.js:20413:14)
      at HTMLUnknownElement.callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (../../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (../../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at safelyCallComponentWillUnmount (../../node_modules/react-dom/cjs/react-dom.development.js:20420:5)
      at commitUnmount (../../node_modules/react-dom/cjs/react-dom.development.js:20951:11)
      at commitNestedUnmounts (../../node_modules/react-dom/cjs/react-dom.development.js:21004:5)
      at unmountHostComponents (../../node_modules/react-dom/cjs/react-dom.development.js:21290:7)
      at commitDeletion (../../node_modules/react-dom/cjs/react-dom.development.js:21347:5)
      at commitMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23407:11)
      at HTMLUnknownElement.callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (../../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (../../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at commitRootImpl (../../node_modules/react-dom/cjs/react-dom.development.js:23121:9)
      at unstable_runWithPriority (../../node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (../../node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at commitRoot (../../node_modules/react-dom/cjs/react-dom.development.js:22990:3)
      at performSyncWorkOnRoot (../../node_modules/react-dom/cjs/react-dom.development.js:22329:3)
      at ../../node_modules/react-dom/cjs/react-dom.development.js:11327:26        
      at unstable_runWithPriority (../../node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (../../node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushSyncCallbackQueueImpl (../../node_modules/react-dom/cjs/react-dom.development.js:11322:9)
      at flushSyncCallbackQueue (../../node_modules/react-dom/cjs/react-dom.development.js:11309:3)
      at batchedUpdates$1 (../../node_modules/react-dom/cjs/react-dom.development.js:22387:7)
      at act (../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (../../node_modules/@testing-library/react/dist/pure.js:97:26)     
      at Object.<anonymous> (src/lib/signature/Signature.spec.tsx:7:5)
      at TestScheduler.scheduleTests (../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../node_modules/@jest/core/build/runJest.js:404:19)
```

</details>

Rendering in the browser seems to work. Any suggestions as to what I'm doing wrong or is this a bug?

**Comment by agilgur5** [comment]
> I am creating a wrapper around the `react-signature-canvas` and am working on writing jest tests for it with `testing-libarary/react`

Wrapper components are definitely encouraged since this is an unopinionated and unstyled component! Everyone's got their own UI components, UX flows, and CSS styles, so I think composition for a more specific use-case is good separation of concerns (while this component handles the generic use-case). When I originally built this component years ago, I also had an internal wrapper around it at my company, with buttons, a modal, `react-bootstrap` integration, etc.
Also tested components great too 👍 

> Rendering in the browser seems to work. Any suggestions as to what I'm doing wrong or is this a bug?

Hard to tell without a reproduction as there's a number of moving pieces here.
I've never seen this error before and a few pieces of your issue hint that this isn't a bug:

1. The stack trace shows that is being hit during _unmounting_ actually. I'm not sure why that's happening, but [`componentWillUnmount`](https://github.com/agilgur5/react-signature-canvas/blob/25ff9077043b35fcf22f1ab14fab755f86532aaf/src/index.js#L40) is being called. That calls the [`off`](https://github.com/agilgur5/react-signature-canvas/blob/25ff9077043b35fcf22f1ab14fab755f86532aaf/src/index.js#L113) method to remove the event listeners.
In the current version of `react-signature-canvas`, the underlying `signature_pad` `ref` starts as [`null`](https://github.com/agilgur5/react-signature-canvas/blob/25ff9077043b35fcf22f1ab14fab755f86532aaf/src/index.js#L27), so from the error message, it sounds like the internal `ref` is `null` during your mount.
The next version of `react-signature-canvas` (the `main` branch) is written in TS and because of the strict typing, actually has [an error check](https://github.com/agilgur5/react-signature-canvas/blob/3db849ff500a3f2f947d46a6100c38aa5b96ac8e/src/index.tsx#L92) if the `ref` is `null`. It's a rare case, but it usually means you're calling a method during a mount/unmount (sounds related, right?)

1. You mentioned that rendering in browser works, so it may very well be your test set-up. Internally, the tests I wrote for this component use [`jsdom`](https://github.com/agilgur5/react-signature-canvas/blob/3db849ff500a3f2f947d46a6100c38aa5b96ac8e/jest.config.ts#L6) and an additional [`window-resizeto` polyfill](https://github.com/agilgur5/window-resizeto) (for mocking the resize functionality). If there's no DOM, a DOM `ref` wouldn't exist, so that could very well break a bunch of things like this.
So I'm not sure what your `jest.config.js` looks like, but my suspicion would be that the test set-up is missing some configuration.

**Comment by agilgur5** [comment]
Looking at the stack trace a bit more, `jsdom` does pop up so I'm assuming you _are_ using `jsdom`?
Also not sure which version of React this is on, as React 18 is currently untested (c.f. #76)

**Comment by AndrewOttavianoAbb** [comment]
@agilgur5 thank you for the quick response! I am using `jsdom` but it is the RTL wrapper around it `import '@testing-library/jest-dom';` I am still on react 17, so that shouldn't be an issue.

**Comment by AndrewOttavianoAbb** [comment]
I am working on getting a repro ready to go. Unfortunately, the project I'm working on is closed source. I am trying to get a codesandbox example but am running into with `fillStyle` which I've [read](https://tnodes.medium.com/setting-up-jest-with-react-and-phaser-422b174ec87e) can be fixed w/`jest-canvas-mock` but am not getting anywhere with that.

Here it is if you want to give it a try: https://codesandbox.io/s/react-17-forked-y43gl3?file=/src/tests/Signature.spec.js

**Comment by agilgur5** [comment]
> I am trying to get a codesandbox example but am running into with `fillStyle` which I've [read](https://tnodes.medium.com/setting-up-jest-with-react-and-phaser-422b174ec87e) can be fixed w/`jest-canvas-mock` but am not getting anywhere with that.

Yea this is probably the crux of the issue -- the `canvas` implementation isn't working.
`react-signature-canvas`'s internal tests [use `node-canvas`](https://github.com/agilgur5/react-signature-canvas/blob/3db849ff500a3f2f947d46a6100c38aa5b96ac8e/package.json#L94), which `jsdom` supports automatically if detected.

> Here it is if you want to give it a try: https://codesandbox.io/s/react-17-forked-y43gl3?file=/src/tests/Signature.spec.js

You're using CRA for this CodeSandbox, so you may very well be running into https://github.com/hustcc/jest-canvas-mock/issues/72 .
I couldn't get it to work in CodeSandbox, and that might be due to requiring native binaries like `node-canvas` etc, or due to CRA issues. Had some issues running in a `node` template (couldn't get things to install), but that may make more sense than the CRA template since Jest runs via Node etc.

I did create a more minimal StackBlitz project for this instead, and the tests pass fine there: https://stackblitz.com/edit/rsc-issue-81?file=index.spec.js .
So I think the issue is within some part of your environment, as a minimal example succeeds.

**Comment by agilgur5** [comment]
Fun fact, apparently I ran into the `fillStyle` issue as well when I was first creating the test suite 3 years ago in https://github.com/agilgur5/react-signature-canvas/issues/33#issuecomment-515737745 .
Using compatible versions of `node-canvas` and `jsdom` resolved it there per that issue.
